/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.microsphere.convert;

import java.io.StringWriter;
import java.util.Properties;

/**
 * The {@link Properties} To {@link String} {@link Converter}
 *
 * @author <a href="mailto:mercyblitz@gmail.com">Mercy</a>
 * @since 1.0.0
 */
public class PropertiesToStringConverter extends AbstractConverter<Properties, String> {

    /**
     * Singleton instance of {@link PropertiesToStringConverter}.
     */
    public static final PropertiesToStringConverter INSTANCE = new PropertiesToStringConverter();

    @Override
    protected String doConvert(Properties source) throws Throwable {
        StringWriter writer = new StringWriter();
        source.store(writer, "Generated by Microsphere");
        return writer.toString();
    }
}
