/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.microsphere.metadata;

import io.microsphere.beans.ConfigurationProperty;

/**
 * The Java SPI of the generator of {@link ConfigurationProperty} that will be generated by
 * Microsphere Annotation Processor module.
 *
 * @author <a href="mailto:mercyblitz@gmail.com">Mercy</a>
 * @see ConfigurationProperty
 * @see io.microsphere.annotation.ConfigurationProperty
 * @since 1.0.0
 */
public interface ConfigurationPropertyGenerator {

    /**
     * Generates a {@link ConfigurationProperty} instance.
     *
     * @return a generated {@link ConfigurationProperty} instance, or {@code null} if no property is generated
     * @throws Throwable if any error occurs during generation
     */
    ConfigurationProperty generate() throws Throwable;
}
