/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.microsphere.metadata;

import io.microsphere.beans.ConfigurationProperty;
import io.microsphere.logging.Logger;

import java.util.List;

import static io.microsphere.collection.ListUtils.newArrayList;
import static io.microsphere.logging.LoggerFactory.getLogger;
import static io.microsphere.util.ClassUtils.getTypeName;
import static io.microsphere.util.ServiceLoaderUtils.loadServicesList;

/**
 * The Java SPI of the generator of {@link ConfigurationProperty} that will be {@link #generateAll generated by}
 * Microsphere Annotation Processor module.
 *
 * @author <a href="mailto:mercyblitz@gmail.com">Mercy</a>
 * @see ConfigurationProperty
 * @see io.microsphere.annotation.ConfigurationProperty
 * @since 1.0.0
 */
public interface ConfigurationPropertyGenerator {

    /**
     * Generates a {@link ConfigurationProperty} instance.
     *
     * @return a generated {@link ConfigurationProperty} instance, or {@code null} if no property is generated
     * @throws Throwable if any error occurs during generation
     */
    ConfigurationProperty generate() throws Throwable;

    /**
     * Generates all {@link ConfigurationProperty} instances by loading and executing all available
     * {@link ConfigurationPropertyGenerator} services via Java SPI mechanism.
     *
     * <h3>Example Usage</h3>
     * <pre>{@code
     * List<ConfigurationProperty> properties = ConfigurationPropertyGenerator.generateAll();
     * for (ConfigurationProperty property : properties) {
     *     System.out.println("Property Name: " + property.getName());
     *     System.out.println("Property Type: " + property.getType());
     *     System.out.println("Property Value: " + property.getValue());
     * }
     * }</pre>
     *
     * @return a list of generated {@link ConfigurationProperty} instances, or an empty list if no generators are found
     * @throws Throwable if any error occurs during generation
     * @see #generate()
     * @see io.microsphere.util.ServiceLoaderUtils#loadServicesList(Class)
     */
    static List<ConfigurationProperty> generateAll() {
        Logger logger = getLogger(ConfigurationPropertyGenerator.class);
        List<ConfigurationPropertyGenerator> generators = loadServicesList(ConfigurationPropertyGenerator.class);
        List<ConfigurationProperty> configurationProperties = newArrayList(generators.size());
        for (ConfigurationPropertyGenerator generator : generators) {
            try {
                ConfigurationProperty configurationProperty = generator.generate();
                configurationProperties.add(configurationProperty);
            } catch (Throwable e) {
                logger.error("Failed to generate the configuration property from {}", getTypeName(generator.getClass()), e);
            }
        }
        return configurationProperties;
    }
}
